version: '3.8'

services:
  # Next.js Application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
      - NEXT_PUBLIC_WS_URL=ws://websocket:3001/ws
      - WEBSOCKET_SERVER_URL=http://websocket:3001
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/projects
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/projects
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - websocket
    command: npm run dev

  # WebSocket Server
  websocket:
    build:
      context: ./websocket-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - ALLOWED_ORIGINS=http://localhost:3000,http://app:3000
      - LOG_LEVEL=info
      - NODE_ENV=development
    volumes:
      - ./websocket-server:/app
      - /app/node_modules
    command: npm run dev

  # Optional: Database (if using PostgreSQL instead of SQLite)
  # database:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_DB=happyrobot
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
